spring:

  datasource:
    username: root
    password: 12345678
    #同样 低版本的MySql不需要指定时区
    url: jdbc:mysql://127.0.0.1:3306/book_dev_01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    #mysql8.0以后的加密方式为caching_sha2_password，所以必须用com.mysql.cj.jdbc.Driver,前提是pom里引入的mysql-connector-java必须为8.0.12的，8.0.13不行，会报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    #如果是老版本的MySql,或者手动修改my.ini指定加密方式为mysql_native_password,则使用原来的Driver即可
    #driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #此连接池配置目前性能较强的连接池